// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuEmV1v6XzMzPLAQOwrsL7R1Kn3Ftzc28',
    appId: '1:547880124958:web:bb3c1cd83b9e15e5f4e40f',
    messagingSenderId: '547880124958',
    projectId: 'fashion-ai-c2c4d',
    authDomain: 'fashion-ai-c2c4d.firebaseapp.com',
    storageBucket: 'fashion-ai-c2c4d.firebasestorage.app',
    measurementId: 'G-VJYDQKPVNN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7doYB4dfhmuW2gmJfD40damQaLx6f6Uo',
    appId: '1:547880124958:android:ec2990c8242bcca3f4e40f',
    messagingSenderId: '547880124958',
    projectId: 'fashion-ai-c2c4d',
    storageBucket: 'fashion-ai-c2c4d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmptCODp0Bdjx-IRd9l5-_WEfGU_Y3utI',
    appId: '1:547880124958:ios:21e6b72b4119a0f8f4e40f',
    messagingSenderId: '547880124958',
    projectId: 'fashion-ai-c2c4d',
    storageBucket: 'fashion-ai-c2c4d.firebasestorage.app',
    androidClientId: '547880124958-j2pajrake71g7n93md2252vehbffgv2o.apps.googleusercontent.com',
    iosClientId: '547880124958-6g84aos3menmotk2al2aeuol72bc2j42.apps.googleusercontent.com',
    iosBundleId: 'com.caglar.fashionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmptCODp0Bdjx-IRd9l5-_WEfGU_Y3utI',
    appId: '1:547880124958:ios:21e6b72b4119a0f8f4e40f',
    messagingSenderId: '547880124958',
    projectId: 'fashion-ai-c2c4d',
    storageBucket: 'fashion-ai-c2c4d.firebasestorage.app',
    androidClientId: '547880124958-j2pajrake71g7n93md2252vehbffgv2o.apps.googleusercontent.com',
    iosClientId: '547880124958-6g84aos3menmotk2al2aeuol72bc2j42.apps.googleusercontent.com',
    iosBundleId: 'com.caglar.fashionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuEmV1v6XzMzPLAQOwrsL7R1Kn3Ftzc28',
    appId: '1:547880124958:web:7d4556ecc56f4835f4e40f',
    messagingSenderId: '547880124958',
    projectId: 'fashion-ai-c2c4d',
    authDomain: 'fashion-ai-c2c4d.firebaseapp.com',
    storageBucket: 'fashion-ai-c2c4d.firebasestorage.app',
    measurementId: 'G-Q2YM6M0DRP',
  );

}